server:
  port: 1237

celesta:
  jdbc:
    url: jdbc:postgresql://localhost:5432/smevdb
    username: postgres
    password: F708420Dx

cron.get.from.smev: 0 0/2 * * * ?

smev.test.case:
  url: http://smev3-n0.test.gosuslugi.ru:7500/smev/v1.1/ws?wsdl
  sg2Url: http://localhost:1235/api/curssmev
  store: CurrentUser/Containers
  alias: REGISTRY\\ISMO_20-21-lipetsk
  storePassword: 12345678
  testInteraction: true
  xmlServiceDir: C:/Users/Sergey/IdeaProjects/smev/Service
